window.portfolioData = {
    name: "Rohit Rawat", title: "System Administrator", email: "rohit35rawat@gmail.com",
    links: { linkedin: "https://linkedin.com/in/rohit-rawat-1b3b39200", github: "https://github.com/rohit-rawat999", portfolio: "https://infosechub.site" },
    nav: ["home", "about", "experience", "skills", "projects", "future", "education", "certifications", "career", "cv", "contact"],
    focus: ["Cloud Infrastructure", "Identity & Access Management", "Cloud Security", "Security Operations"],
    services: [
        ["IT Infrastructure", "Windows Server, Active Directory, Group Policy, DNS, DHCP, VMware and infrastructure troubleshooting."],
        ["Microsoft 365", "Microsoft 365 administration, Exchange Online, mailboxes, permissions, mail flow and troubleshooting."],
        ["Identity & Access Management", "Microsoft Entra ID, MFA, Conditional Access, identity administration and access troubleshooting."],
        ["Endpoint Management", "Microsoft Intune, device enrollment, compliance and endpoint troubleshooting."],
        ["Security", "Microsoft Defender, CrowdStrike, Trend Micro, endpoint security and email security."],
        ["Backup & Recovery", "Veeam, Commvault, backup monitoring, restore validation and recovery processes."],
        ["Automation", "PowerShell and infrastructure automation."],
        ["Cloud", "AWS/Azure learning and hands-on labs focused on cloud infrastructure, IAM and security."]
    ],
    experience: [
        { role: "System Administrator", company: "Comnet Innovations Pvt. Ltd.", dates: "Jul 2025 – Present", type: "REAL PROFESSIONAL EXPERIENCE", items: ["Windows & Linux server administration, health checks and incident troubleshooting", "VMware ESXi / vCenter administration and virtual machine operations", "Active Directory user, group, OU and access administration", "Group Policy creation, troubleshooting and policy validation", "DNS, DHCP and core Windows infrastructure troubleshooting", "Microsoft 365 administration including Exchange Online mailboxes, permissions and mail flow", "Microsoft Entra ID administration, MFA, RBAC and sign-in troubleshooting", "Microsoft Intune device enrollment, compliance and configuration troubleshooting", "Conditional Access policy administration and access-control troubleshooting", "Veeam and Commvault backup monitoring, job troubleshooting and restore validation", "Endpoint security operations using Microsoft Defender, CrowdStrike and Trend Micro", "PowerShell scripting for administration and repetitive operational tasks", "ServiceNow ticket handling, incident updates and SLA-focused resolution", "Infrastructure troubleshooting, root-cause analysis and cross-team coordination"] },
        { role: "L2 Desktop Support Engineer", company: "SBI Card via Quess/Digitide", dates: "Jan 2024 – Jun 2025", type: "REAL PROFESSIONAL EXPERIENCE", items: ["Enterprise end-user support across corporate Windows endpoints", "Windows OS, application and performance troubleshooting", "Desktop, laptop, printer and peripheral hardware support", "Active Directory user access, group membership and account troubleshooting", "Microsoft 365 user support and application troubleshooting", "VPN connectivity, remote-access and authentication troubleshooting", "BitLocker and endpoint security support", "MFA and user authentication issue resolution", "Endpoint security agent and policy-related troubleshooting", "ServiceNow incident, request and change-ticket handling", "User onboarding, access troubleshooting and operational support", "SLA-focused incident resolution and clear technical documentation"] }
    ],
    skills: [
        ["Infrastructure", "Windows Server", "Hands-on"], ["Infrastructure", "Active Directory", "Hands-on"], ["Infrastructure", "Group Policy", "Hands-on"], ["Infrastructure", "DNS", "Hands-on"], ["Infrastructure", "DHCP", "Hands-on"], ["Infrastructure", "File Server", "Working Knowledge"], ["Infrastructure", "VMware ESXi", "Hands-on"], ["Infrastructure", "vCenter", "Hands-on"],
        ["Microsoft", "Microsoft 365", "Hands-on"], ["Microsoft", "Exchange Online", "Hands-on"], ["Microsoft", "Microsoft Entra ID", "Hands-on"], ["Microsoft", "Intune", "Hands-on"], ["Microsoft", "MFA", "Hands-on"], ["Microsoft", "Conditional Access", "Hands-on"],
        ["Security", "Microsoft Defender", "Working Knowledge"], ["Security", "CrowdStrike", "Working Knowledge"], ["Security", "Trend Micro", "Working Knowledge"], ["Security", "Endpoint Security", "Hands-on"], ["Security", "Email Security", "Working Knowledge"], ["Security", "IAM", "Working Knowledge"],
        ["Backup", "Veeam", "Hands-on"], ["Backup", "Commvault", "Hands-on"], ["Backup", "Backup & Restore", "Hands-on"], ["Backup", "3-2-1 Backup Strategy", "Working Knowledge"],
        ["Cloud", "AWS", "Learning"], ["Cloud", "Azure", "Learning"], ["Cloud", "IAM", "Learning"], ["Cloud", "EC2", "Hands-on"], ["Cloud", "S3", "Learning"], ["Cloud", "CloudTrail", "Hands-on"], ["Cloud", "CloudWatch", "Learning"], ["Cloud", "Terraform", "Learning"],
        ["Automation", "PowerShell", "Hands-on"], ["Automation", "IT Automation", "Working Knowledge"]
    ],
    caseSteps: ["Verified administrative roles", "Investigated the 401 permission/session issue", "Used a clean browser session", "Reviewed Mobility > Microsoft Intune configuration", "Checked automatic enrollment configuration", "Changed “Disable MDM enrollment when adding work or school account on Windows” from Yes to No", "Changed WIP user scope from All to None", "Saved configuration", "Triggered enrollment/check-in using the documented method", "Validated device enrollment"],
    projects: [
        { id: 1, title: "AWS Secure EC2 & IAM", domain: "Cloud", status: "Completed", type: "Hands-on Lab", description: "Built a hands-on AWS environment using EC2, IAM roles and instance profiles, VPC, Secrets Manager, KMS, CloudTrail, and CloudWatch. Practiced least-privilege access and secure credential management.", tech: ["AWS EC2", "IAM", "IAM Roles", "Instance Profiles", "VPC", "Secrets Manager", "KMS", "CloudTrail", "CloudWatch"], purpose: "Hands-on cloud infrastructure and access-control practice.", implementation: "Configured an EC2-centered AWS lab using role-based access, networking, secrets and monitoring components.", security: "Least-privilege IAM and secure credential management were the focus.", result: "Hands-on lab completed." },
        { id: 2, title: "AWS VPC & Network Security", domain: "Cloud", status: "Completed", type: "Hands-on Lab", description: "Designed a hands-on VPC environment with public/private subnets, route tables, Internet Gateway, NAT, security groups, and NACLs. Practiced EC2 connectivity and network troubleshooting.", tech: ["AWS VPC", "Public Subnet", "Private Subnet", "Route Tables", "Internet Gateway", "NAT", "Security Groups", "NACLs", "EC2"], purpose: "Network segmentation and connectivity practice.", implementation: "Designed public/private subnet routing and tested EC2 connectivity boundaries.", security: "Used security groups and NACLs as separate control layers.", result: "Hands-on lab completed." },
        { id: 3, title: "Microsoft Entra ID & IAM", domain: "IAM", status: "Completed", type: "Hands-on Lab", description: "Practiced Entra ID identity administration including users, groups, MFA, RBAC, SSO, Conditional Access, sign-in troubleshooting, and least-privilege access.", tech: ["Microsoft Entra ID", "IAM", "MFA", "RBAC", "SSO", "Conditional Access"], purpose: "Identity administration and access-control practice.", implementation: "Worked through identities, access policies and sign-in troubleshooting scenarios.", security: "Least-privilege access and MFA were central to the lab.", result: "Hands-on lab completed." },
        { id: 4, title: "Microsoft 365 Administration", domain: "Microsoft 365", status: "Completed", type: "Hands-on Lab", description: "Practiced Exchange Online administration including mailboxes, shared mailboxes, distribution groups, permissions, mail flow, and Microsoft 365 troubleshooting.", tech: ["Microsoft 365", "Exchange Online", "Mailboxes", "Shared Mailboxes", "Distribution Groups", "Permissions", "Mail Flow"], purpose: "Microsoft 365 and Exchange administration practice.", implementation: "Practiced mailbox lifecycle, permissions and mail-flow troubleshooting.", security: "Focused on controlled access and permission troubleshooting.", result: "Hands-on lab completed." },
        { id: 5, title: "Microsoft Defender & Endpoint Security", domain: "Security", status: "Completed", type: "Hands-on Lab", description: "Practiced endpoint security scenarios involving Microsoft Defender, phishing investigation, quarantine, suspicious activity investigation, and security monitoring.", tech: ["Microsoft Defender", "Endpoint Security", "Phishing Investigation", "Quarantine", "Security Monitoring"], purpose: "Endpoint security investigation practice.", implementation: "Worked through investigation and response scenarios for suspicious endpoint and email activity.", security: "Focused on investigation, quarantine and monitoring workflows.", result: "Hands-on lab completed." },
        { id: 6, title: "Microsoft Intune Device Management", domain: "Endpoint", status: "Completed", type: "Hands-on Lab", description: "Practiced device enrollment, configuration policies, compliance policies, application deployment, and endpoint-management troubleshooting.", tech: ["Microsoft Intune", "Device Enrollment", "Configuration Policies", "Compliance Policies", "Application Deployment"], purpose: "Endpoint management practice.", implementation: "Practiced enrollment, policy delivery, compliance and application-management workflows.", security: "Used compliance and configuration controls as management guardrails.", result: "Hands-on lab completed." },
        { id: 7, title: "Active Directory Administration", domain: "Infrastructure", status: "Completed", type: "Hands-on Lab", description: "Built a Windows Server AD environment and practiced users, groups, OUs, GPOs, DNS/DHCP dependencies, authentication, access control, and identity troubleshooting.", tech: ["Windows Server", "Active Directory", "Users & Groups", "OUs", "GPO", "DNS", "DHCP", "Authentication"], purpose: "Directory services administration practice.", implementation: "Built and administered a Windows Server Active Directory lab.", security: "Practiced authentication and access-control fundamentals.", result: "Hands-on lab completed." },
        { id: 8, title: "Linux Server Administration", domain: "Infrastructure", status: "Completed", type: "Hands-on Lab", description: "Practiced Ubuntu/Linux administration including users and groups, permissions, SSH, systemd services, networking, logs, and server troubleshooting.", tech: ["Linux", "Ubuntu", "Users & Groups", "Permissions", "SSH", "systemd", "Networking", "Logs"], purpose: "Linux administration and troubleshooting practice.", implementation: "Practiced common server administration and troubleshooting workflows on Ubuntu/Linux.", security: "Focused on permissions, SSH and service hygiene.", result: "Hands-on lab completed." }
    ],
    futureProjects: [["Cloud IAM Security Lab", "PLANNED"], ["Azure Identity & Access Management Lab", "PLANNED"], ["Cloud Security Monitoring Lab", "PLANNED"], ["Terraform Infrastructure Automation", "PLANNED"], ["SIEM / Security Monitoring Lab", "PLANNED"]],
    education: [["BCA — Cyber Security", "2024 – Present"], ["Diploma in Cloud Computing", "2023 – 2024"]],
    certifications: [["PREPARING", "Microsoft SC-300"], ["LEARNING", "Cloud, IAM and Security Operations"]]
};