(() => {
    const d = window.portfolioData, $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)]; const toast = m => { const t = $("#toast"); t.textContent = m; t.classList.add("show"); clearTimeout(window.__toast); window.__toast = setTimeout(() => t.classList.remove("show"), 1600) }; $("#year").textContent = new Date().getFullYear();
    d.nav.forEach(id => { const label = id === "home" ? "Home" : id[0].toUpperCase() + id.slice(1); const a = document.createElement("a"); a.href = "#" + id; a.textContent = label; a.dataset.nav = id; $("#navLinks").append(a); const m = a.cloneNode(true); $("#mobileMenu").append(m) });
    d.focus.forEach(x => { const e = document.createElement("div"); e.className = "focus-item"; e.textContent = x; $("#focusList").append(e) });
    d.services.forEach((s, i) => { const e = document.createElement("article"); e.className = "service glass reveal"; e.innerHTML = '<span class="service-num">0' + (i + 1) + '</span><h3>' + s[0] + '</h3><p>' + s[1] + '</p>'; $("#serviceGrid").append(e) });
    d.experience.forEach(e => { const el = document.createElement("article"); el.className = "timeline-card glass reveal"; el.tabIndex = 0; el.innerHTML = '<div class="timeline-top"><div><div class="timeline-role">' + e.role + '</div><div class="timeline-company">' + e.company + '</div></div><div style="text-align:right"><div class="timeline-date">' + e.dates + '</div><span class="badge">' + e.type + '</span></div></div><div class="timeline-items">' + e.items.map(x => '<span>' + x + '</span>').join("") + '</div>'; $("#experienceTimeline").append(el) });
    function filters(id, items, handler) { const box = $(id); items.forEach(x => { const b = document.createElement("button"); b.className = "filter" + (x === "All" ? " active" : ""); b.textContent = x; b.type = "button"; b.onclick = () => { $$(id + " .filter").forEach(q => q.classList.remove("active")); b.classList.add("active"); handler(x) }; box.append(b) }) }
    const skillCats = ["All", "Infrastructure", "Microsoft", "Security", "Backup", "Cloud", "Automation"]; let skillFilter = "All";
    function renderSkills() { const q = $("#skillSearch").value.toLowerCase(); const groups = {}; d.skills.filter(s => (skillFilter === "All" || s[0] === skillFilter) && s[1].toLowerCase().includes(q)).forEach(s => (groups[s[0]] ??= []).push(s.slice(1))); $("#skillGrid").innerHTML = Object.entries(groups).map(([cat, items]) => '<article class="skill-panel glass reveal"><h3>' + cat + '</h3><div class="skill-items">' + items.map(x => '<div class="skill-item"><span>' + x[0] + '</span><span class="level">' + x[1] + '</span></div>').join("") + '</div></article>').join("") || '<div class="glass" style="grid-column:1/-1;padding:24px;border-radius:20px;color:var(--muted)">No matching technologies.</div>'; observe() }
    filters("#skillFilters", skillCats, x => { skillFilter = x; renderSkills() }); $("#skillSearch").oninput = renderSkills; renderSkills();
    const projectCats = ["All", "Infrastructure", "Microsoft 365", "IAM", "Security", "Cloud", "Endpoint"]; let projectFilter = "All"; filters("#projectFilters", projectCats, x => { projectFilter = x; renderProjects() });
    function renderProjects() { const q = $("#projectSearch").value.toLowerCase(); const arr = d.projects.filter(p => (projectFilter === "All" || p.domain === projectFilter) && (p.title + " " + p.domain + " " + p.tech.join(" ")).toLowerCase().includes(q)); $("#projectGrid").innerHTML = arr.map(p => '<article class="project glass reveal" data-id="' + p.id + '" tabindex="0"><div class="project-top"><span class="pill">' + p.type + '</span><span class="domain">' + p.domain + '</span></div><h3>' + p.title + '</h3><p>' + p.description + '</p><div class="tech-list">' + p.tech.slice(0, 6).map(t => '<span class="tech">' + t + '</span>').join("") + '</div></article>').join("") || '<div class="glass" style="grid-column:1/-1;padding:24px;border-radius:20px;color:var(--muted)">No matching projects.</div>'; observe(); $$(".project").forEach(el => { el.onclick = () => openProject(+el.dataset.id); el.onkeydown = e => { if (e.key === "Enter" || e.key === " ") openProject(+el.dataset.id) } }) }
    $("#projectSearch").oninput = renderProjects; renderProjects();
    d.futureProjects.forEach(x => { const e = document.createElement("article"); e.className = "future glass reveal"; e.innerHTML = '<span>' + x[1] + '</span><h3>' + x[0] + '</h3><p>Planned work — not represented as completed professional experience.</p>'; $("#futureGrid").append(e) });
    d.education.forEach(x => { const e = document.createElement("article"); e.className = "education glass reveal"; e.innerHTML = '<span class="eyebrow">EDUCATION</span><h3>' + x[0] + '</h3><p>' + x[1] + '</p>'; $("#educationGrid").append(e) });
    d.certifications.forEach(x => { const e = document.createElement("article"); e.className = "learning glass reveal"; e.innerHTML = '<span class="eyebrow">' + x[0] + '</span><h3>' + x[1] + '</h3><p>Current learning status is shown explicitly; no completion claim is implied.</p>'; $("#certGrid").append(e) });
    const links = [["LinkedIn", "Professional profile and career updates.", d.links.linkedin], ["GitHub", "Projects, labs and technical work.", d.links.github], ["Portfolio", "Complete professional profile and documentation.", d.links.portfolio], ["Email", "Direct contact.", "mailto:" + d.email]]; links.forEach(x => { const e = document.createElement("article"); e.className = "connect glass reveal"; e.innerHTML = '<div><strong>' + x[0] + '</strong><p>' + x[1] + '</p></div><a href="' + x[2] + '" ' + (x[2].startsWith("http") ? 'target="_blank" rel="noreferrer"' : '') + '>' + (x[0] === "Email" ? d.email : "Open " + x[0] + " ↗") + '</a>'; $("#connectGrid").append(e) });
    $("#caseSteps").innerHTML = d.caseSteps.map(x => "<li>" + x + "</li>").join("");
    function openProject(id) { const p = d.projects.find(x => x.id === id); $("#modalPill").textContent = p.type.toUpperCase(); $("#modalContent").innerHTML = '<h2 id="modalTitle">' + p.title + '</h2><p><strong>' + p.domain + '</strong> · ' + p.status + '</p><div class="modal-grid"><div class="modal-block"><b>Problem / Purpose</b><p>' + p.purpose + '</p></div><div class="modal-block"><b>Implementation</b><p>' + p.implementation + '</p></div><div class="modal-block"><b>Technologies</b><p>' + p.tech.join(" · ") + '</p></div><div class="modal-block"><b>Security considerations</b><p>' + p.security + '</p></div><div class="modal-block"><b>Learning / Result</b><p>' + p.result + '</p></div><div class="modal-block"><b>Documentation</b><p>Not added</p><b>GitHub</b><p>Not added</p></div></div>'; $("#projectModal").hidden = false; document.body.style.overflow = "hidden"; $("#modalClose").focus() } function closeModal() { $("#projectModal").hidden = true; document.body.style.overflow = "" } $("#modalClose").onclick = closeModal; $("#projectModal").onclick = e => { if (e.target === $("#projectModal")) closeModal() };
    const sections = d.nav.map(id => document.getElementById(id)).filter(Boolean); const navs = $$(".nav-links a,.mobile-menu a"); const io = new IntersectionObserver(es => es.forEach(e => { if (e.isIntersecting) navs.forEach(a => a.classList.toggle("active", a.dataset.nav === e.target.id)) }), { rootMargin: "-35% 0px -55% 0px" }); sections.forEach(s => io.observe(s));
    function observe() { const ro = new IntersectionObserver(es => es.forEach(e => { if (e.isIntersecting) { e.target.classList.add("in"); ro.unobserve(e.target) } }), { threshold: .08 }); $$(".reveal:not(.in)").forEach(x => ro.observe(x)) } observe();
    addEventListener("scroll", () => { const h = document.documentElement.scrollHeight - innerHeight; $("#progress").style.width = (scrollY / Math.max(h, 1) * 100) + "%"; $(".nav").classList.toggle("scrolled", scrollY > 40); $("#backTop").style.opacity = scrollY > 600 ? "1" : ".55" });
    $("#backTop").onclick = () => scrollTo({ top: 0, behavior: "smooth" }); $("#themeBtn").onclick = () => { const warm = document.documentElement.dataset.theme !== "warm"; document.documentElement.dataset.theme = warm ? "warm" : ""; document.documentElement.style.setProperty("--accent", warm ? "#D6C7A1" : "#7FE3A4"); document.documentElement.style.setProperty("--accent2", warm ? "#F0E6CC" : "#B8F2CA") };
    $(".copy-email").onclick = async () => { try { await navigator.clipboard.writeText(d.email); toast("Copied!") } catch { toast(d.email) } };
    const commands = [["Home", "home"], ["Go About", "about"], ["Go Experience", "experience"], ["Go Skills", "skills"], ["Go Projects", "projects"], ["Go Contact", "contact"], ["Open GitHub", d.links.github], ["Open LinkedIn", d.links.linkedin], ["Email Rohit", "mailto:" + d.email]];
    function renderCmd(q) { const arr = commands.filter(x => x[0].toLowerCase().includes((q || "").toLowerCase())); $("#cmdList").innerHTML = arr.map((x, i) => '<div class="cmd-item" data-i="' + i + '"><span>' + x[0] + '</span><span>↵</span></div>').join(""); $$(".cmd-item").forEach(el => el.onclick = () => runCmd(arr[+el.dataset.i][1])) } function runCmd(v) { $("#commandOverlay").hidden = true; if (v.startsWith("http")) window.open(v, "_blank", "noopener"); else if (v.startsWith("mailto:")) location.href = v; else document.getElementById(v)?.scrollIntoView({ behavior: "smooth", block: "start" }) } function openPalette() { renderCmd(""); $("#commandOverlay").hidden = false; $("#cmdSearch").value = ""; $("#cmdSearch").focus() } $("#cmdSearch").oninput = e => renderCmd(e.target.value); $("#cmdClose").onclick = () => $("#commandOverlay").hidden = true; $("#commandOverlay").onclick = e => { if (e.target === $("#commandOverlay")) $("#commandOverlay").hidden = true };
    addEventListener("keydown", e => { if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "k") { e.preventDefault(); openPalette() } if (e.key === "Escape") { closeModal(); $("#commandOverlay").hidden = true; $("#mobileMenu").hidden = true; $("#menuBtn").setAttribute("aria-expanded", "false") } });
    $("#menuBtn").onclick = () => { $("#mobileMenu").hidden = !$("#mobileMenu").hidden; document.body.classList.toggle("menu-open", !$("#mobileMenu").hidden); $("#menuBtn").setAttribute("aria-expanded", String(!$("#mobileMenu").hidden)) }; $("#mobileMenu").onclick = e => { if (e.target.closest("a")) { $("#mobileMenu").hidden = true; document.body.classList.remove("menu-open"); $("#menuBtn").setAttribute("aria-expanded", "false") } };
    addEventListener("DOMContentLoaded", () => { if ("scrollRestoration" in history) history.scrollRestoration = "manual"; if (!location.hash) scrollTo(0, 0); else setTimeout(() => document.querySelector(location.hash)?.scrollIntoView({ block: "start" }), 0) });
    const hv = $("#heroVisual"); addEventListener("pointermove", e => { if (innerWidth < 900 || matchMedia("(prefers-reduced-motion: reduce)").matches) return; const r = hv.getBoundingClientRect(), x = (e.clientX - r.left - r.width / 2) / r.width, y = (e.clientY - r.top - r.height / 2) / r.height; hv.style.transform = "translate(" + (x * 7) + "px," + (y * 7) + "px)" }); addEventListener("pointerleave", () => { if (innerWidth >= 900) hv.style.transform = "" });
})();